name = "duckduckgo-ai"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

[dev]
ip = "127.0.0.1"

[vars]
API_KEY = "sk-sjsknxjeisowlchurs1937xbxnskw7"

[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "8d5f25255e894a549af76faade93191e"
